### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by leo**
This PR introduces a few subtle changes to the project's file and configuration structure to make it compatible with the current best practises around the web.

### CODE REVIEW

**Comment by leo** [comment]
The reason why the test is failing because the `TEST_NOW_TOKEN` env variable is missing.

**Comment by timolins** [comment]
Awesome work, Leo! I will merge it as soon as possible...

**Comment by leo** [comment]
Whoops! Forgot to delete the "lib" directory after renaming the build directory to "dist". Can you please do that? 😄

**Comment by timolins** [comment]
Of course, thank you! 😊

**Pull request merged**
